networks:
  default:
    name: rapptor
    external: true
volumes:
  rapptor-user-data:
    external: true
services:
  app.rapptor.transmission:
    container_name: app.rapptor.transmission
    image: linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/etc:/config:rw
      - rapptor-user-data:/files:rw
    expose:
      - 9091
    ports:
      - 58119:58119
    healthcheck:
      test: curl -f http://localhost:9091 || exit 1
      interval: 30s
      retries: 3
      start_interval: 1s
      start_period: 30s
      timeout: 10s
    logging:
      driver: none
