#! /bin/env bash

set -e

INSTANCE_NAME="$1"
VIRTUAL_FOLDERS_RESPONSE=$(curl -s 'http://localhost:8096/Library/VirtualFolders' \
  -H 'accept: application/json'
)

if ! echo "$VIRTUAL_FOLDERS_RESPONSE" | grep '{"Path":"/files/Downloads"}' > /dev/null; then
  curl 'http://localhost:8096/Startup/Configuration' \
  -H 'Content-Type: application/json' \
  --data-raw "{\"ServerName\":\"$INSTANCE_NAME\",\"UICulture\":\"en-US\",\"MetadataCountryCode\":\"US\",\"PreferredMetadataLanguage\":\"en\"}"

  curl -s 'http://localhost:8096/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Movies' \
    -H 'Content-Type: application/json' \
    --data-raw '{"LibraryOptions":{"Enabled":true,"EnableArchiveMediaFiles":false,"EnablePhotos":true,"EnableRealtimeMonitor":true,"EnableLUFSScan":true,"ExtractTrickplayImagesDuringLibraryScan":false,"SaveTrickplayWithMedia":false,"EnableTrickplayImageExtraction":false,"ExtractChapterImagesDuringLibraryScan":false,"EnableChapterImageExtraction":false,"EnableInternetProviders":true,"SaveLocalMetadata":false,"EnableAutomaticSeriesGrouping":false,"PreferredMetadataLanguage":"","MetadataCountryCode":"","SeasonZeroDisplayName":"Specials","AutomaticRefreshIntervalDays":0,"EnableEmbeddedTitles":false,"EnableEmbeddedExtrasTitles":false,"EnableEmbeddedEpisodeInfos":false,"AllowEmbeddedSubtitles":"AllowAll","SkipSubtitlesIfEmbeddedSubtitlesPresent":false,"SkipSubtitlesIfAudioTrackMatches":false,"SaveSubtitlesWithMedia":true,"SaveLyricsWithMedia":false,"RequirePerfectSubtitleMatch":true,"AutomaticallyAddToCollection":false,"PreferNonstandardArtistsTag":false,"UseCustomTagDelimiters":false,"MetadataSavers":[],"TypeOptions":[{"Type":"Movie","MetadataFetchers":["TheMovieDb","The Open Movie Database"],"MetadataFetcherOrder":["TheMovieDb","The Open Movie Database"],"ImageFetchers":["TheMovieDb","The Open Movie Database","Embedded Image Extractor","Screen Grabber"],"ImageFetcherOrder":["TheMovieDb","The Open Movie Database","Embedded Image Extractor","Screen Grabber"]}],"LocalMetadataReaderOrder":["Nfo"],"SubtitleDownloadLanguages":[],"CustomTagDelimiters":["/","|",";","\\"],"DelimiterWhitelist":[],"DisabledSubtitleFetchers":[],"SubtitleFetcherOrder":[],"DisabledLyricFetchers":[],"LyricFetcherOrder":[],"PathInfos":[{"Path":"/files/Movies"},{"Path":"/files/Downloads"}]}}'

  curl -s 'http://localhost:8096/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=false&name=TV%20Shows' \
    -H 'Content-Type: application/json' \
    --data-raw '{"LibraryOptions":{"Enabled":true,"EnableArchiveMediaFiles":false,"EnablePhotos":true,"EnableRealtimeMonitor":true,"EnableLUFSScan":true,"ExtractTrickplayImagesDuringLibraryScan":false,"SaveTrickplayWithMedia":false,"EnableTrickplayImageExtraction":false,"ExtractChapterImagesDuringLibraryScan":false,"EnableChapterImageExtraction":false,"EnableInternetProviders":true,"SaveLocalMetadata":false,"EnableAutomaticSeriesGrouping":false,"PreferredMetadataLanguage":"","MetadataCountryCode":"","SeasonZeroDisplayName":"Specials","AutomaticRefreshIntervalDays":0,"EnableEmbeddedTitles":false,"EnableEmbeddedExtrasTitles":false,"EnableEmbeddedEpisodeInfos":false,"AllowEmbeddedSubtitles":"AllowAll","SkipSubtitlesIfEmbeddedSubtitlesPresent":false,"SkipSubtitlesIfAudioTrackMatches":false,"SaveSubtitlesWithMedia":true,"SaveLyricsWithMedia":false,"RequirePerfectSubtitleMatch":true,"AutomaticallyAddToCollection":false,"PreferNonstandardArtistsTag":false,"UseCustomTagDelimiters":false,"MetadataSavers":[],"TypeOptions":[{"Type":"Series","MetadataFetchers":["TheMovieDb","The Open Movie Database"],"MetadataFetcherOrder":["TheMovieDb","The Open Movie Database"],"ImageFetchers":["TheMovieDb"],"ImageFetcherOrder":["TheMovieDb"]},{"Type":"Season","MetadataFetchers":["TheMovieDb"],"MetadataFetcherOrder":["TheMovieDb"],"ImageFetchers":["TheMovieDb"],"ImageFetcherOrder":["TheMovieDb"]},{"Type":"Episode","MetadataFetchers":["TheMovieDb","The Open Movie Database"],"MetadataFetcherOrder":["TheMovieDb","The Open Movie Database"],"ImageFetchers":["TheMovieDb","The Open Movie Database","Embedded Image Extractor","Screen Grabber"],"ImageFetcherOrder":["TheMovieDb","The Open Movie Database","Embedded Image Extractor","Screen Grabber"]}],"LocalMetadataReaderOrder":["Nfo"],"SubtitleDownloadLanguages":[],"CustomTagDelimiters":["/","|",";","\\"],"DelimiterWhitelist":[],"DisabledSubtitleFetchers":[],"SubtitleFetcherOrder":[],"DisabledLyricFetchers":[],"LyricFetcherOrder":[],"PathInfos":[{"Path":"/files/TV Shows"},{"Path":"/files/Downloads"}]}}'

  curl -s 'http://localhost:8096/Library/VirtualFolders?collectionType=music&refreshLibrary=false&name=Music' \
    -H 'Content-Type: application/json' \
    --data-raw '{"LibraryOptions":{"Enabled":true,"EnableArchiveMediaFiles":false,"EnablePhotos":true,"EnableRealtimeMonitor":true,"EnableLUFSScan":true,"ExtractTrickplayImagesDuringLibraryScan":false,"SaveTrickplayWithMedia":false,"EnableTrickplayImageExtraction":false,"ExtractChapterImagesDuringLibraryScan":false,"EnableChapterImageExtraction":false,"EnableInternetProviders":true,"SaveLocalMetadata":false,"EnableAutomaticSeriesGrouping":false,"PreferredMetadataLanguage":"","MetadataCountryCode":"","SeasonZeroDisplayName":"Specials","AutomaticRefreshIntervalDays":0,"EnableEmbeddedTitles":false,"EnableEmbeddedExtrasTitles":false,"EnableEmbeddedEpisodeInfos":false,"AllowEmbeddedSubtitles":"AllowAll","SkipSubtitlesIfEmbeddedSubtitlesPresent":false,"SkipSubtitlesIfAudioTrackMatches":false,"SaveSubtitlesWithMedia":true,"SaveLyricsWithMedia":false,"RequirePerfectSubtitleMatch":true,"AutomaticallyAddToCollection":false,"PreferNonstandardArtistsTag":false,"UseCustomTagDelimiters":false,"MetadataSavers":[],"TypeOptions":[{"Type":"MusicArtist","MetadataFetchers":["MusicBrainz"],"MetadataFetcherOrder":["TheAudioDB","MusicBrainz"],"ImageFetchers":["TheAudioDB"],"ImageFetcherOrder":["TheAudioDB"]},{"Type":"MusicAlbum","MetadataFetchers":["MusicBrainz"],"MetadataFetcherOrder":["MusicBrainz","TheAudioDB"],"ImageFetchers":["TheAudioDB"],"ImageFetcherOrder":["TheAudioDB"]},{"Type":"Audio","ImageFetchers":["Image Extractor"],"ImageFetcherOrder":["Image Extractor"]},{"Type":"MusicVideo","ImageFetchers":["Embedded Image Extractor","Screen Grabber"],"ImageFetcherOrder":["Embedded Image Extractor","Screen Grabber"]}],"LocalMetadataReaderOrder":["Nfo"],"SubtitleDownloadLanguages":[],"CustomTagDelimiters":["/","|",";","\\"],"DelimiterWhitelist":[],"DisabledSubtitleFetchers":[],"SubtitleFetcherOrder":[],"DisabledLyricFetchers":[],"LyricFetcherOrder":[],"PathInfos":[{"Path":"/files/Music"},{"Path":"/files/Downloads"}]}}'
fi

