networks:
  default:
    name: rapptor
    external: true
volumes:
  rapptor-data:
    external: true
services:
  app.93million.nextcloud:
    image: nextcloud:31.0.5-apache
    container_name: app.93million.nextcloud
    volumes:
      - rapptor-data:/files:rw
      - ./nextcloud:/var/www/html:rw
      - ./scripts:/scripts:ro
    environment:
      NEXTCLOUD_ADMIN_USER: 'admin'
      NEXTCLOUD_ADMIN_PASSWORD: 'qwer1234'
      SQLITE_DATABASE: 'sqlite'
      NEXTCLOUD_TRUSTED_DOMAINS: "app-93million-nextcloud.${RAPPTOR_BASE_DOMAIN}"
      OVERWRITEPROTOCOL: https
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:80 || exit 1
      interval: 30s
      retries: 3
      start_interval: 2s
      start_period: 30s
      timeout: 10s
  app.93million.nextcloud.cron:
    image: nextcloud:31.0.5-apache
    container_name: app.93million.nextcloud.cron
    volumes:
      - ./nextcloud:/var/www/html
      - rapptor-data:/files:rw
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "app-93million-nextcloud.${RAPPTOR_BASE_DOMAIN}"
      OVERWRITEPROTOCOL: https
    restart: unless-stopped
    entrypoint: /cron.sh
