networks:
  default:
    name: rapptor
    external: true

volumes:
  rapptor-user-data:
    external: true
  rapptor-tls-certs:
    external: true
  jellyfincache:
  jellyfinconfig:

services:
  app.93million.jellyfin:
    image: jellyfin/jellyfin:10.11.1
    container_name: app.93million.jellyfin
    user: 1000:1000
    volumes:
      - jellyfinconfig:/config
      - jellyfincache:/cache
      - rapptor-user-data:/files
      - ./scripts:/scripts:ro
    restart: unless-stopped
    environment:
      JELLYFIN_PublishedServerUrl: "https://app-93million-jellyfin.${RAPPTOR_BASE_DOMAIN}"
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      interval: 30s
      retries: 3
      start_interval: 1s
      start_period: 30s
      test: "( curl --noproxy 'localhost' -Lk -fsS 'http://localhost:8096/health' && (test $(curl -s -o /dev/null -w '%{http_code}' 'http://localhost:8096/Startup/Configuration') -eq 401 || test $(curl -s -o /dev/null -w '%{http_code}' 'http://localhost:8096/Startup/Configuration') -eq 200) ) || exit 1"
  app.93million.jellyfin.nginx:
    image: nginx
    container_name: app.93million.jellyfin.nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - rapptor-tls-certs:/etc/ssl/rapptor:ro
    ports:
      - 8920:8920
    restart: unless-stopped
