networks:
  default:
    name: rapptor
    external: true
volumes:
  rapptor-user-data:
    external: true
  owncloud-www:
  owncloud-data:
services:
  app.93million.owncloud:
    image: ghcr.io/93million/rapptor.app.93million.owncloud:10.16.1
    container_name: app.93million.owncloud
    volumes:
      - rapptor-user-data:/files:rw
      - owncloud-data:/mnt/data:rw
    environment:
      OWNCLOUD_DOMAIN: "app-93million-owncloud.${RAPPTOR_BASE_DOMAIN}"
      OWNCLOUD_ADMIN_USER: 'admin'
      OWNCLOUD_ADMIN_PASSWORD: '#{randomStr(42)}'
      OWNCLOUD_DB_TYPE: sqlite
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_TRUSTED_DOMAINS: "app-93million-owncloud.${RAPPTOR_BASE_DOMAIN}"
      OVERWRITEPROTOCOL: https
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
      interval: 30s
      retries: 3
      start_interval: 1s
      start_period: 120s
      timeout: 10s
