networks:
  default:
    name: rapptor
    external: true
volumes:
  rapptor-data:
    external: true
services:
  app.93million.plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: app.93million.plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ./data/config:/config:rw
      - rapptor-data:/files:rw
    ports:
      - 32400:32400/tcp
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:32400/web/index.html || exit 1
      interval: 60s
      retries: 3
      start_interval: 2s
      start_period: 30s
      timeout: 10s
